[profile.default]
src = "src"
out = "artifacts"
libs = ["node_modules", "lib"]
remappings = [
    "@aave/=node_modules/@aave/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
    'src/=src/',
]
solc-version = "0.8.10"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
libraries = [
    "src/core/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x6a5840EBCd333231FFfa5823c551518D0E51af12",
    "src/core/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0x33D2009360ff026A889eD157b5d7F4b24d63e85b",
    "src/core/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x545694B6431445dc8F6D2c936A327B633B0383Eb",
    "src/core/protocol/libraries/logic/EModeLogic.sol:EModeLogic:0x80E38713D23b42d7Ff194b31D079477FD4b631FD",
    "src/core/protocol/libraries/logic/BridgeLogic.sol:BridgeLogic:0x58da15A838672ab4900C11B1202ca6a2905eb3bA",
    "src/core/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0x061105764d8AA7d40E8d64d08d664961ff3A9330",
    "src/core/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0x5c0730619A820D42C79b8e2c6641Ef8AB40a41f0",
    "src/core/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0x771bD3591c90B945e47c46FD9EfC994fe2048E12",
    ]
[etherscan]
t_opBNB = { key = "${TOPBNB_ETHERSCAN_API_KEY}", chain=5611, url="https://open-platform.nodereal.io/${NODEREAL_KEY}/op-bnb-testnet/contract/" }
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", chain=56, url="https://api.bscscan.com/api"}
chapel = { key = "${CHAPEL_ETHERSCAN_API_KEY}", chain=97, url="https://api-testnet.bscscan.com/api"}

[default.rpc_endpoints]
bsc = "https://bsc-dataseed1.binance.org/"
chapel = "https://data-seed-prebsc-1-s1.binance.org:8545/"

[profile.wombat]
test = 'test/ATokenStaker/WombatStaker'

[profile.magpie]
test = 'test/ATokenStaker/MagpieStaker'